version: '3'

services:
  posts:
    build: ./posts-service
    ports:
      - "3000:3000"
  
  comments:
    build: ./comments-service
    ports:
      - "3001:3001"
  
  event-bus:
    build: ./event-bus-service
    ports:
      - "3002:3002"

  moderation:
    build: ./moderation-service
    ports:
      - "3003:3003"

  query:
    build: ./query-service
    ports:
      - "3004:3004"
